const fs = require('fs');
const path = require('path');
const os = require('os');
const { sleep } = require('./browser');
const demo = require('./demo');
module.exports = [{ name: 'theme-studio', async run(t) {
  const b = await t.open({ demo: false });
  const base = await b.eval('return location.origin'), token = await b.eval('return TOKEN');
  const wire = async browser => {
    await browser.intercept('*/api/*', async (url, method, data) => {
      if (!new URL(url).pathname.startsWith('/api/themes')) return null;
      const r = await fetch(url, { method, headers: { 'x-switcher-token': token, 'content-type': 'application/json' }, ...(method === 'POST' ? { body: data } : {}) });
      return { status: r.status, type: r.headers.get('content-type'), body: Buffer.from(await r.arrayBuffer()) };
    });
    await demo.install(browser); await browser.nav(base + '/');
  };
  await wire(b);
  await b.eval('openSetup("look"); return 1'); await b.clickOn('[data-studio-open]'); await sleep(300);
  t.check('Studio opens from Appearance and keeps the current theme', await b.eval('return studioDlg.open && Look.get().theme === "crimson" && !!studioWorld'));
  await b.eval(`studioName.value='Lantern Tide'; studioWorld.value='A quiet seaside town with warm paper lanterns and turquoise water'; studioFont.value='storybook'; window.oldStudioOpen=ChatUI.open; ChatUI.open=async o=>{window.studioBrief=o}; studioForm.requestSubmit(); return 1`); await sleep(1000);
  const draft = await b.eval('return studioBrief');
  t.check('generation prepares a Codex brief in its own workspace without sending a message', draft?.provider === 'codex' && draft?.mode === 'new' && draft?.initialText.includes('theme.json LAST') && draft?.cwd.includes('theme-studio'));
  await b.eval('ChatUI.open=oldStudioOpen; return 1');
  await b.eval(`await ThemeStudio.open();window.savedStudioApi=api;api=async (...args)=>{const r=await savedStudioApi(...args);if(args[0]==='/api/themes/create')await new Promise(r=>setTimeout(r,600));return r;};ChatUI.open=async()=>{window.canceledStudioOpened=true};studioName.value='Canceled world';studioWorld.value='A peaceful forest';studioForm.requestSubmit();return 1`);
  await b.esc(); await sleep(1000);
  t.check('closing Studio while a brief is being prepared cancels the chat launch', await b.eval('return !window.canceledStudioOpened && !studioDlg.open'));
  await b.eval(`api=savedStudioApi;ChatUI.open=async()=>{throw new Error('Studio test: Codex could not start')};await ThemeStudio.open();return 1`);
  await b.clickOn('[data-studio-resume]'); await sleep(300);
  t.check('a failed art chat shows its error even after the studio dialog closes', await b.eval(`return document.getElementById('toast').textContent.includes('Studio test: Codex could not start')`));
  await b.eval('ChatUI.open=oldStudioOpen; return 1');
  const jobs = await b.eval('return (await api("/api/themes")).jobs'), j = jobs.find(x => x.name === 'Lantern Tide');
  const rel = path.relative(os.tmpdir(), draft.cwd);
  if (rel.startsWith('..') || path.isAbsolute(rel) || !draft.cwd.endsWith(j.id)) throw new Error('Test art workspace is outside the throwaway server data directory');
  let png;
  if (!process.env.STUDIO_ART) png = Buffer.from(await b.eval(`const im = new Image(); im.src='/art/isekai-dark.webp'; await im.decode(); const c=document.createElement('canvas'); c.width=1536;c.height=1024;c.getContext('2d').drawImage(im,0,0,1536,1024);return c.toDataURL('image/png').split(',')[1]`), 'base64');
  for (const mode of ['dark', 'light']) fs.writeFileSync(path.join(draft.cwd, mode + '.png'), process.env.STUDIO_ART ? fs.readFileSync(path.join(process.env.STUDIO_ART, mode + '.png')) : png);
  fs.writeFileSync(path.join(draft.cwd, 'theme.json'), JSON.stringify({ name: 'Lantern Tide', note: 'Lanterns above a quiet sea, from moonlight to morning.', font: 'storybook', seeds: { accent: 184, sat: .8, surface: 207, surfSat: .7, ink: 190, inkSat: .4, gold: 39, codex: 268 }, copy: { 'Welcome back': 'The shore welcomes you' } }));
  await b.eval('await ThemeStudio.open(); return 1'); await b.clickOn('[data-studio-review]'); await sleep(1200);
  t.check('both decoded paintings and measured contrast appear before saving', await b.eval(`return document.querySelectorAll('.studio-sample').length===2 && [...document.querySelectorAll('.studio-sample img')].every(i=>i.complete&&i.naturalWidth) && /Small text/.test(studioBody.textContent) && Look.get().theme==='crimson'`));
  await t.shot(b, 'preview');
  await b.esc();
  t.check('closing a preview leaves the current theme unchanged', await b.eval('return !studioDlg.open && Look.get().theme === "crimson"'));
  await b.eval(`await ThemeStudio.open();await ThemeStudio.review(${JSON.stringify(j.id)});return 1`);
  await b.clickOn('[data-studio-save]'); await sleep(1000);
  t.check('save applies the theme and writes real WebP assets in the data folder', await b.eval(`return Look.get().theme===${JSON.stringify(j.id)} && (await api('/api/themes')).themes.some(t=>t.id===Look.get().theme)`));
  await b.eval('setup.close(); go("hub"); return 1'); await sleep(400);
  for (const mode of ['dark', 'light']) {
    await b.eval(`Look.set({mode:${JSON.stringify(mode)}});return 1`); await sleep(250);
    const s = await b.eval(`const i=document.querySelector('.studio-scene img');return {image:i?.complete&&i.naturalWidth>0,url:i?.src,counts:document.querySelector('.studio-counts')?.textContent,audit:Look.audit(Look.theme())}`);
    t.check(`${mode} scene uses its own protected painting and clear live counts`, s.image && s.url.includes('mode=' + mode) && /need you/.test(s.counts) && s.audit[mode].faint >= 4.5 && s.audit[mode].body >= 7, s);
    await t.shot(b, 'hub-' + mode);
  }
  await b.nav(base + '/'); await sleep(500);
  t.check('a saved custom theme survives a reload', await b.eval(`return Look.theme().id===${JSON.stringify(j.id)} && !!document.querySelector('.studio-scene img')`));
  const art = `${base}/api/themes/art?kind=themes&id=${j.id}&mode=dark`;
  t.check('private paintings cannot be fetched without authentication', (await fetch(art)).status === 403);
  t.check('the protected image route accepts the page token', (await fetch(art + '&token=' + token)).status === 200);
  t.check('a token cannot turn an art URL into a filesystem reader', (await fetch(`${base}/api/themes/art?kind=themes&id=../accounts&mode=dark&token=${token}`)).status === 400);
  const p = await t.open({ width: 390, height: 844, mobile: true, demo: false }); await wire(p);
  await p.eval(`await ThemeStudio.refresh();Look.set({theme:${JSON.stringify(j.id)},mode:'dark'});return 1`); await sleep(300);
  t.check('phone scene fits without horizontal overflow', await p.eval('return document.scrollingElement.scrollWidth<=innerWidth+1 && document.querySelector(".studio-scene").getBoundingClientRect().width<=innerWidth'));
  await t.shot(p, 'phone-hub');
  await p.eval('await ThemeStudio.open(); return 1');
  t.check('the phone studio and saved library fit the screen', await p.eval('return studioDlg.getBoundingClientRect().right<=innerWidth && studioBody.scrollWidth<=studioBody.clientWidth+1'));
  await t.shot(p, 'phone-studio');
  await p.eval('S.codex.signedIn=false;await ThemeStudio.open();return 1');
  t.check('signed-out users can use saved worlds but cannot start image generation', await p.eval('return studioForm.querySelector("[type=submit]").disabled && !document.querySelector("[data-studio-use]").disabled'));
  await b.send('Performance.enable');
  const metrics = async () => Object.fromEntries((await b.send('Performance.getMetrics')).result.metrics.map(x => [x.name,x.value]));
  const m0=await metrics();await sleep(1600);const m1=await metrics();
  t.check('custom paintings have no perpetual layout animation', (m1.LayoutCount-m0.LayoutCount)/(m1.Timestamp-m0.Timestamp)<6);
  await b.eval(`await api('/api/themes/delete',{id:${JSON.stringify(j.id)}});await ThemeStudio.refresh();return 1`);
  await p.eval('await ThemeStudio.refresh();return 1');
  t.check('deleting an active theme falls back on both devices', await b.eval('return Look.get().theme==="crimson"') && await p.eval('return Look.get().theme==="crimson"'));
} }];
